name: Build Snippets Docker Image
on:
  workflow_dispatch:
  push:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  dev_build:
    uses: epichouse/github-templates/.github/workflows/docker_build.yaml@main
    with:
      image_tag: development
      image_name: snippets
      build_path: ./
  dev_deploy:
    uses: epichouse/github-templates/.github/workflows/docker_pull.yaml@main
    needs: dev_build
    with:
      docker_server: ldnapptst1
      docker_compose_project: snippets-test
  prod_build:
    uses: epichouse/github-templates/.github/workflows/docker_build.yaml@main
    needs: dev_deploy
    with:
      image_tag: latest
      image_name: snippets
      build_path: ./
  prod_deploy:
    uses: epichouse/github-templates/.github/workflows/docker_pull.yaml@main
    needs: prod_build
    with:
      docker_server: ldnappprd1
      docker_compose_project: snippets